### PR TITLE
Allow for custom encoders and decoders

### PR DESCRIPTION
**Pull request by commjoen**
This could be a potential solution for https://github.com/socketio/socket.io-client-java/issues/333 .

### CODE REVIEW

**Comment by nkzawa** [comment]
hi, thanks for your PR, but I wonder when actually you'd like to modify encoder/decoder.
Basically, I think it wouldn't be a good idea to allow customizing socket.io protocol / data frame.

**Comment by commjoen** [comment]
We want to have additional payload-encryption on top of the socket.io protocol. This means that we have to extend the encoder/decoder with additional crypto.

**Comment by nkzawa** [comment]
I think you can just encrypt sending data instead of encrypting whole packet. Any reasons that doesn't work on your case ?

**Comment by commjoen** [comment]
We rather encrypt every frame in order to make sure that handshakes can not be intercepted in case of broken SSL.

**Comment by nkzawa** [comment]
I wonder if you can't test broken SSL before connecting to socket.io server.
I'd like to make sure this is inevitable to support.

**Comment by nkzawa** [comment]
Custom encoder and decoder will be supported by https://github.com/socketio/socket.io-client-java/pull/439, since socket.io v2 supports it now. Thanks for the PR.

**Pull request closed without merging**
