### PR TITLE
Fixed #245

### LINKED ISSUE #245: jitter not correctly calculated during backoff
backoff is not working correctly:

    public long duration() {
        long ms = this.ms * (long) Math.pow(this.factor, this.attempts++);
        if (jitter != 0.0) {
            double rand = Math.random();
            int deviation = (int) Math.floor(rand * this.jitter * ms);
            ms = (((int) Math.floor(rand * 10)) & 1) == 0 ? ms - deviation : ms + deviation;
        }
        if (ms < this.ms) {
            // overflow happened
            ms = Long.MAX_VALUE;
        }
        return Math.min(ms, this.max);
    }

On the first attempt (and dependent on `this.jitter`) `ms` may become smaller than `this.ms`, which ultimately leads to `this.max` being assigned to `ms`. In turn, the first reconnect attempt will not happen after the minimum backoff time as expected, but after the maximum time. This leads to a long period during which we are disconnected.

I would possibly scrap the overflow test 

        if (ms < this.ms) {
            // overflow happened
            ms = Long.MAX_VALUE;
        }
        return Math.min(ms, this.max);

and return `ms` as is:

        return ms;

This may lead to the first reconnect happening before `this.min`. If that is a problem [which - if I apply the idea of random jitter values logically correct - is not], I would add a possibly negative deviation instead of subtracting it, but **never** set `ms = Long.MAX_VALUE`.

BTW: Deviation is calculated from `ms`. I believe it should be calculated from `this.min`. Otherwise we may get quite large values, for example a maximum reconnection time of 15 secs may end up as 22.5 secs with a jitter setting of .5.

I didn't change the code as I am not deep enough into this as to know the implications of what I am doing, but I am quite sure we have a bug here.

### PR DESCRIPTION
**Pull request by oliverhausler**
I have removed the defective overflow calculation, in case you want to merge.

### CODE REVIEW

**Comment by nkzawa** [comment]
Thanks for your PR, but checking max limit and overflow are required. I'd like to fix the issue without modifying the behavior .

**Comment by oliverhausler** [comment]
The problem is that the math is obviously wrong. You are checking for an underrun (ms < min), and when it occurs set ms to max (instead of min).

That means, backoff starts out with max ms if this happens and a reconnect does not occur in reasonable time.

If you can't go under min, then at least you should set ms to min, not to max, or an I seeing this wrong?


-------- Original message --------
From: Naoyuki Kanezawa
Date:2015/11/10 21:29 (GMT-08:00)
To: "socketio/socket.io-client-java"
Cc: Oliver Hausler
Subject: Re: [socket.io-client-java] Fixed #245 (#246)


Thanks for your PR, but checking max limit and overflow are required. I'd like to fix the issue without modifying the behavior .

**Comment by nkzawa** [comment]
`if (ms < this.ms) {` is intended to fix https://github.com/socketio/socket.io-client-java/issues/107.

So we have to fix the way to detect number overflow rather than changing the behavior.

**Comment by oliverhausler** [comment]
Yes, so the bug seems to be in the formula to calculate deviation. I haven't looked into this, but the numbers are rather large sometimes.

How is jitter defined? jitter = .5 means what?

ms in = 1000 -> ms out = 500..1500
ms in = 2000 -> ms out = 1500..2500 or 1000..3000 ?

**Comment by oliverhausler** [comment]
I made the following assumption for the fix I posted:

ms in = 2000 -> ms out = 1000..3000

**Comment by nkzawa** [comment]
Thanks but it looks overflowed number become `min`?

**Comment by nkzawa** [comment]
Fixed in https://github.com/socketio/socket.io-client-java/commit/8c29b2ef9c68fd524932c15ac7851f80fdea47cc. Thanks!!!

**Pull request closed without merging**
