### PR TITLE
Emit with timeout

### PR DESCRIPTION
**Pull request by kristiyanP**
## PROBLEM
Our socket.io implementation requires the ability to know if an emit will eventually have a return callback or not in a pre-defined time.

This behaviour of not knowing if eventually you will receive a callback is also applied if the server is not even listening for that emit!

Feature requested in issue: #309

## SOLUTION
Socket.io swift client has a good implementation of this feature, but to port it in the java client would require a huge refactor. 

See [SocketIOClient.emitWithAck:with](https://nuclearace.github.io/Socket.IO-Client-Swift/Classes/SocketIOClient.html#/c:@M@SocketIO@objc(cs)SocketIOClient(im)emitWithAck:with:)

**I implemented what I believe is the smallest possible change to the actual library, in order to have this feature**

* created AckWithTimeOut class which implements Ack interface.
* When used with AckWithTimeOut the timer starts directly and is paused and restarts (from 0) when the socket disconnects and when reconnects.
* The timers are cancelled in case of a dispose of the socket.
* When a timeout has occurred a NoAck object will be returned to the user of the library.

## TESTING
* 2 new methods to cover generic use cases noack and noackWithReconnect.
* All other tests pass.

## NOTICE
This feature may not be easly achieved if implemented outside of socket.io-client-java, if we consider the reconnection use-case.
* External interface has **not changed**.
* Internal Ack interface is now an abstract class using the method callback() instead of call() to cancel the timer and keep the obligation of implemention of the old interface.

### CODE REVIEW

**Comment by snowb1shop** [comment]
Does anyone know when will it be merged?

**Comment by kristiyanP** [comment]
It's there from a year and it's a really small change. 
The project is not really active...
If you need it we released a version of socket.io with it
`implementation("com.bandyer:socket.io-client:1.0.9")`

**Comment by snowb1shop** [comment]
Thank you, we will check this out 👍

**Comment by kristiyanP** [comment]
@darrachequesne I just have seen that you are the new maintainer of the project. Is this PR still valid?

**Comment by darrachequesne** [comment]
Merged as https://github.com/socketio/socket.io-client-java/commit/fca3b9507d5bc79d3c41ab6e119efccd23669ca6 (better late than never...).

I went for a slightly different API:

```java
socket.emit("hello", "world", new AckWithTimeout(5000) {
    @Override
    public void onTimeout() {
        // ...
    }

    @Override
    public void onSuccess(Object... args) {
        // ...
    }
});
```

instead of

```java
socket.emit("hello", "world", new AckWithTimeout(5000) {
    @Override
    public void call(Object... args) {
        if (args[0] instanceof NoAck) {
            // ...
        } else {
            // ...
        }
    }
});
```

Included in version `2.1.0`. We could also backport it to 1.x, if needed.

**Pull request closed without merging**
